version: '3.8'
services:
  amidb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
   
  sm1:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - amidb
    ports:
      - 8901:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

volumes:
  mongodb-data: