version: '3.8'
services:
  smart-meter-db:
        image: mcr.microsoft.com/azure-sql-edge
        container_name: 
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=ryankruger45
        ports:
          - "1433:1433"
        volumes:
          - /etc/smdb:/var/opt/mssql/data
   
  sm1:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - amidb
    ports:
      - 8901:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

volumes:
  mongodb-data: